### ISSUE TITLE
Still crashing after 2838283 reflashes and rebootes

### ISSUE THREAD

**Issue by joao-201** [reiryuki/Dolby-Atmos-OnePlus-8-Visible-Magisk-Module#3]
Usin mi 9 miui 12.5 android 11 and Nlsound module which allows to use built in dirac with Dolby. other Dolby works and there is the crash report:

java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.settingslib.bluetooth.A2dpProfile com.android.settingslib.bluetooth.LocalBluetoothProfileManager.getA2dpProfile()' on a null object reference
	at com.oneplus.sound.tuner.SoundTunerService.getConnectedA2dpDevices(SoundTunerService.java:692)
	at com.oneplus.sound.tuner.SoundTunerService.findActiveDevice(SoundTunerService.java:737)
	at com.oneplus.sound.tuner.SoundTunerService.findMediaOutputDevice(SoundTunerService.java:437)
	at com.oneplus.sound.tuner.SoundTunerService.access$1500(SoundTunerService.java:55)
	at com.oneplus.sound.tuner.SoundTunerService$2.run(SoundTunerService.java:379)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:249)
	at android.app.ActivityThread.main(Unknown Source:134)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:313)

**Comment by reiryuki** [comment]
Explained in troubleshootings
